micronaut:
  application:
    name: travellog

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Ahjutagune7
    schema-generate: NONE
    dialect: POSTGRES
liquibase:
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/liquibase-changelog.xml'
      drop-first: true
